### ISSUE TITLE
Is there a way to back up the internal SD card manually?

### ISSUE THREAD

**Issue by Botts85** [bassrock/AVIC-NEX#2]
Hello,

I was hoping to try my hand at some AVIC hacking, but wanted to back up a known good internal SD card before I began.

Is there a way to image the SD card if I already have it out of an AVIC?  I was hoping to just DD the raw device to a backup image.  However, when I tried this, the SD card won't show up in Ubuntu, Kali, macOS, or Windows, so I can't copy it. 

Any ideas on backing it up without using the script on device?

**Comment by bassrock** [comment]
http://avic411.com/index.php?/topic/81468-the-avic-development-mod/ Will be your best resource. along with the slack community. https://avicsignup.herokuapp.com/
